// Package files stores uploaded documents and photographs.
//
// Locally they go on disk under UPLOAD_DIR. In the deployed system they go to
// S3. The Storage interface is the seam between the two, so switching does not
// touch a single handler.
//
// Nothing here is reachable by guessing a URL. A stored file is named by a
// random key, and the only way to read one is through a handler that has
// already checked the caller's role — because these are birth certificates and
// photographs of children.
package files

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"mime"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Storage is somewhere files can be put and fetched.
type Storage interface {
	// Save writes the contents and returns the storage key.
	Save(key string, contents io.Reader) error
	// Open returns a reader for a stored file.
	Open(key string) (io.ReadCloser, error)
	// Delete removes a stored file.
	Delete(key string) error
}

// ErrNotStored is returned when a key does not exist.
var ErrNotStored = errors.New("file is not in storage")

// LocalStorage keeps files on the machine running the API.
type LocalStorage struct {
	root string
}

// NewLocalStorage prepares the upload directory.
func NewLocalStorage(root string) (*LocalStorage, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("resolve upload directory: %w", err)
	}
	// 0o700: only the user running the API can read these. They are student
	// records, not web assets.
	if err := os.MkdirAll(absolute, 0o700); err != nil {
		return nil, fmt.Errorf("create upload directory %s: %w", absolute, err)
	}
	return &LocalStorage{root: absolute}, nil
}

// Root is where files are being written, for the start-up log.
func (l *LocalStorage) Root() string { return l.root }

func (l *LocalStorage) path(key string) (string, error) {
	// The key is generated by this package, never taken from a request, but
	// check anyway: one day someone will pass a key through from user input,
	// and "../../etc/passwd" should fail here rather than work.
	if key == "" || strings.Contains(key, "..") || filepath.IsAbs(key) {
		return "", fmt.Errorf("%w: unsafe key %q", ErrNotStored, key)
	}

	full := filepath.Join(l.root, filepath.FromSlash(key))

	// Belt and braces: the resolved path must still be inside the root.
	relative, err := filepath.Rel(l.root, full)
	if err != nil || strings.HasPrefix(relative, "..") {
		return "", fmt.Errorf("%w: key escapes the upload directory", ErrNotStored)
	}
	return full, nil
}

// Save writes a file, creating the year/month directories it lives in.
func (l *LocalStorage) Save(key string, contents io.Reader) error {
	full, err := l.path(key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(full), 0o700); err != nil {
		return fmt.Errorf("create directory for %s: %w", key, err)
	}

	// O_EXCL so a colliding key fails loudly instead of overwriting somebody
	// else's birth certificate.
	file, err := os.OpenFile(full, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return fmt.Errorf("create %s: %w", key, err)
	}
	defer file.Close()

	if _, err := io.Copy(file, contents); err != nil {
		// Do not leave a half-written document behind.
		_ = os.Remove(full)
		return fmt.Errorf("write %s: %w", key, err)
	}
	return file.Sync()
}

// Open returns a reader for a stored file.
func (l *LocalStorage) Open(key string) (io.ReadCloser, error) {
	full, err := l.path(key)
	if err != nil {
		return nil, err
	}
	file, err := os.Open(full)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, fmt.Errorf("%w: %s", ErrNotStored, key)
		}
		return nil, fmt.Errorf("open %s: %w", key, err)
	}
	return file, nil
}

// Delete removes a stored file. A missing file is not an error: the caller's
// intent was for it to be gone.
func (l *LocalStorage) Delete(key string) error {
	full, err := l.path(key)
	if err != nil {
		return err
	}
	if err := os.Remove(full); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("delete %s: %w", key, err)
	}
	return nil
}

// NewKey builds a storage key for an upload.
//
// Shape: 2026/10/<32 random hex chars><extension>. The date prefix keeps any
// one directory from filling up with tens of thousands of entries; the random
// name means a key cannot be guessed from a student's name or admission number,
// and two uploads of "photo.jpg" never collide.
func NewKey(category, originalName string) (string, error) {
	random := make([]byte, 16)
	if _, err := rand.Read(random); err != nil {
		return "", fmt.Errorf("generate file key: %w", err)
	}

	extension := strings.ToLower(filepath.Ext(originalName))
	if !allowedExtensions[extension] {
		extension = ""
	}

	now := time.Now()
	safeCategory := sanitiseSegment(category)

	return fmt.Sprintf("%s/%04d/%02d/%s%s",
		safeCategory, now.Year(), int(now.Month()),
		hex.EncodeToString(random), extension), nil
}

// allowedExtensions are the ones kept on the stored filename. Anything else is
// stored without an extension, so a .php or .html upload cannot be served as
// one even by accident.
var allowedExtensions = map[string]bool{
	".jpg": true, ".jpeg": true, ".png": true, ".webp": true, ".heic": true,
	".pdf": true, ".csv": true, ".xlsx": true, ".xls": true, ".txt": true,
}

// AllowedMIMETypes are the content types an upload may declare.
//
// A school uploads photographs of documents, PDFs, and the occasional
// spreadsheet for a bulk import. Nothing executable, and no SVG — an SVG is a
// document that can carry script, and it would be served back to other users.
var AllowedMIMETypes = map[string]bool{
	"image/jpeg":      true,
	"image/png":       true,
	"image/webp":      true,
	"image/heic":      true,
	"image/heif":      true,
	"application/pdf": true,
	"text/csv":        true,
	"text/plain":      true,
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": true,
	"application/vnd.ms-excel": true,
}

// IsImage reports whether a MIME type is one of the image formats, which is
// what the gallery and photograph fields accept.
func IsImage(mimeType string) bool {
	return strings.HasPrefix(mimeType, "image/") && AllowedMIMETypes[mimeType]
}

// ContentTypeFor guesses a content type from a stored key, for the download
// handler's response header.
func ContentTypeFor(key string) string {
	if byExtension := mime.TypeByExtension(filepath.Ext(key)); byExtension != "" {
		return byExtension
	}
	return "application/octet-stream"
}

func sanitiseSegment(value string) string {
	cleaned := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '_':
			return r
		case r >= 'A' && r <= 'Z':
			return r + 32
		default:
			return -1
		}
	}, value)

	if cleaned == "" {
		return "misc"
	}
	if len(cleaned) > 32 {
		return cleaned[:32]
	}
	return cleaned
}
